# version: '3.8'

services:
  app:
    build: ./app/
    image: karpov-app
    env_file:
      # - ./app/.env  # файл с переменными окружения
      - .env
    volumes:
      - ./app:/app  # исходный файл приложения
    depends_on:
      - rabbitmq
      - database
    restart: on-failure
    networks:
      - backend

  worker:
    build:  ./app/services/RabbitMQ/
    image: ml-worker
    env_file:
      - .env
    volumes:
      - ./app/services/RabbitMQ:/app
      - ../modelses:/app/modelses
    working_dir: /app/services/RabbitMQ #/app/app/services/RabbitMQ
    # working_dir: /app  # корневая директория
    # command: python services/RabbitMQ/worker.py  # полный путь к файлу
    depends_on:
      - rabbitmq
      - database
    restart: unless-stopped
    networks:
      - backend
    command: python worker.py

  web-proxy:
    image: nginx:alpine  # Используем готовый образ
    # build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped  # on-failure
    networks:
      - backend
      - frontend

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure
    networks:
      - backend

  database:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}  # это пока пример, я потом после прохождения БД подправлю
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: on-failure
    networks:
      - backend

volumes:
  rabbitmq_data:
#    driver: local  # Используется локальный драйвер
#    driver_opts:   # Дополнительные настройки драйвера
#      type: none
#      o: bind
#      device: /path/to/rabbitmq_data  # путь

  mysql_data:
#    driver: local  # Используется локальный драйвер
#    driver_opts:   # Дополнительные настройки драйвера
#      type: none
#      o: bind

networks:
    backend:
    frontend: